    CC     = gcc -g -std=c11
    CFLAGS = 
    LFLAGS = -lm

      PROG = main 


.PHONY: limpa faxina clean purge all

%.o: %.c %.h utils.h
	$(CC) -c $(CFLAGS) 

limpa clean:
	@rm -f *~ *.bak

faxina purge:   limpa
	@rm -f *.o core a.out
	@rm -f $(PROG)
